const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("orion", {
  appVersion: () => ipcRenderer.invoke("app:version"),
  elevate: () => ipcRenderer.invoke("app:elevate"),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  saveSettings: (settings) => ipcRenderer.invoke("settings:save", settings),
  login: (credentials) => ipcRenderer.invoke("auth:login", credentials),
  logout: () => ipcRenderer.invoke("auth:logout"),
  catalog: () => ipcRenderer.invoke("catalog:get"),
  profile: () => ipcRenderer.invoke("system:profile"),
  preview: (tweak) => ipcRenderer.invoke("tweak:preview", tweak),
  apply: (tweak) => ipcRenderer.invoke("tweak:apply", tweak),
  activeOptimizations: () => ipcRenderer.invoke("optimizations:active"),
  clearActiveOptimization: (tweakId) => ipcRenderer.invoke("optimizations:clear", tweakId),
  sessions: () => ipcRenderer.invoke("history:list"),
  rollback: (session) => ipcRenderer.invoke("history:rollback", session),
  games: (options) => ipcRenderer.invoke("games:list", options),
  launchGame: (game) => ipcRenderer.invoke("game:launch", game),
  performance: (options) => ipcRenderer.invoke("performance:snapshot", options),
  displays: (options) => ipcRenderer.invoke("display:list", options),
  internalOverview: () => ipcRenderer.invoke("internal:overview"),
  internalUsers: () => ipcRenderer.invoke("internal:users"),
  internalUserAction: (payload) => ipcRenderer.invoke("internal:userAction", payload),
  openPortal: (pathname) => ipcRenderer.invoke("portal:open", pathname),
  minimize: () => ipcRenderer.send("window:minimize"),
  maximize: () => ipcRenderer.send("window:maximize"),
  close: () => ipcRenderer.send("window:close"),
});
